# Generated by Django 3.2.4 on 2021-12-01 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('description', models.TextField()),
                ('create_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('thumbnail_1', models.ImageField(upload_to='media')),
                ('thumbnail_2', models.ImageField(upload_to='media')),
                ('thumbnail_3', models.ImageField(upload_to='media')),
                ('thumbnail_4', models.ImageField(upload_to='media')),
            ],
        ),
    ]
