# Generated by Django 3.2.4 on 2021-12-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_create_at_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('time', models.DateField()),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
            ],
        ),
    ]
