# Generated by Django 3.2.4 on 2021-12-24 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_socialmedia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
