# Generated by Django 3.2.4 on 2021-12-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
