# Generated by Django 3.2.4 on 2021-12-06 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_latestnew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
